# Generated by Django 4.0.4 on 2022-04-17 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=100)),
                ('agencia_origem', models.CharField(max_length=4)),
                ('conta_origem', models.CharField(max_length=7)),
                ('banco_destino', models.CharField(max_length=100)),
                ('agencia_destino', models.CharField(max_length=4)),
                ('conta_destino', models.CharField(max_length=7)),
                ('valor_transacao', models.FloatField()),
                ('data_transacao', models.DateTimeField()),
                ('data_upload', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
