# Generated by Django 4.0.4 on 2022-04-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0003_rename_usuario_importacao_user'),
        ('transacoes', '0002_transacao_importacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='importacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='importacoes.importacao'),
        ),
    ]
