# Generated by Django 4.0.4 on 2022-04-17 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transacoes', models.DateTimeField()),
                ('data_importacao', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
