# Generated by Django 4.0.4 on 2022-05-02 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importacoes', '0003_rename_usuario_importacao_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importacao',
            options={'verbose_name_plural': 'importações'},
        ),
        migrations.AlterField(
            model_name='importacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
