# Generated by Django 4.0.4 on 2022-04-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0003_rename_usuario_importacao_user'),
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='importacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='importacoes.importacao'),
            preserve_default=False,
        ),
    ]
