# Generated by Django 4.0.4 on 2022-04-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0002_importacao_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importacao',
            old_name='usuario',
            new_name='user',
        ),
    ]
